#!/bin/bash
#  This file is part of oppikoppi.
#  Copyright (C) 2021 Anssi Gröhn

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# This script runs robot framework script, which downloads moodle logs from yesterday using special account
# and converts them into xAPI statements locally, and sends them forth to local learning locker instance.
# Script assumes X is running :0.0
prevPWD=$PWD
LOGDIR=/var/log/oppikoppi

cd /path/to/oppikoppi-robot
MAX_ATTEMPTS=3
attempt=0
success=0
# by default, fetch from yesterday
fixeddate=$(date  +%Y-%m-%d --date yesterday)
if [ $# -gt 0 ]; then
    fixeddate=$1
    logger Running fetch-logs-to-learning-locker for ${fixeddate}
else
    logger Running fetch-logs-to-learning-locker for yesterday
fi

# Persistency for connection errors.
# Try until script succeeds, or maximum number of attempts is reached
while [[ ${success} -eq 0 && ${attempt} -lt ${MAX_ATTEMPTS} ]]; do
    DISPLAY=:0.0 robot --exitonfailure --variable FirstTimeDownloadAll:True --variable Date:${fixeddate} -o ${LOGDIR}/log.xml -l ${LOGDIR}/log-FAIL-${fixeddate}.html -r NONE fetch-moodle-data.robot
    if [ $? -eq 0 ]; then
	success=1
    fi
    attempt=`expr $attempt + 1`
done
# report errors, if any
if [ ${success} -eq 0 ]; then
   logger fetch-logs-to-learninglocker FAIL
else
    logger fetch-logs-to-learninglocker SUCCESS
    /bin/rm -f ${LOGDIR}/log-FAIL-${fixeddate}.html
fi
cd $prevPWD
