#!/bin/bash
#  This file is part of oppikoppi.
#  Copyright (C) 2021 Anssi Gröhn

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# This script runs robot framework script, which downloads moodle logs from yesterday using special account
# and converts them into xAPI statements locally, and sends them forth to local learning locker instance.

# This script runs command that downloads a specific course attempt data from learning locker into shared onedrive.

prevPWD=$PWD
datadir="/path/to/powerbi-data"
MAX_ATTEMPTS=5
logger Running $0
cd /path/to/oppikoppi-robot

courses=`cat ${datadir}/active-courses.txt`
# Update only single course, if specified
if [ ! $# -eq 0 ]; then
    courses=$1
    echo "Updating only single course $courses"
fi

# Copies default data over retrieved ones if retrieved data was empty
# Ensures that Power Bi has something to fetch.
function UseDefaultDataIfNeeded()
{
    course=$1
    name=$2
    file_size=$(wc -c < ${datadir}/${course}_${name}.json)

    if [ ${file_size} -eq 2 ]; then
	cp ${datadir}/XXXX_${name}.json ${datadir}/${course}_${name}.json
    fi
}


for course in ${courses}; do

    attempt_num=0
    success=0
    while [[ ${attempt_num} -lt ${MAX_ATTEMPTS} && ${success} -eq 0 ]]; do
	echo "Running attempt ${attempt_num} for course ${course}..."
	su -c "./helper-scripts/ll-submissions.sh --id ${course} \
       	  		       --scores    ${datadir}/${course}_attempts.json \
			       --submissions ${datadir}/${course}_submissions.json \
			       --submissions-by-date ${datadir}/${course}_submissions_bydate.json \
			       --activity    ${datadir}/${course}_activity.json \
			       --firstactivity    ${datadir}/${course}_firstactivity.json \
			       --students    ${datadir}/${course}_students.json \
			       --sessions    ${datadir}/${course}_sessions.json \
			       --assignments    ${datadir}/${course}_assignments.json \
			       --force" LOCAL_USER
	if [ $? -eq 0 ]; then
	    success=1
	fi
	attempt_num=`expr ${attempt_num} + 1`
	
    done

    # Place default data if nothing was found 
    for dataname in activity attempts firstactivity sessions students submissions submissions_bydate; do
	UseDefaultDataIfNeeded ${course} ${dataname}
    done

    # Log end state
    if [ ${success} -ne 0 ]; then
	logger $0 SUCCESS ${course}
    else
	logger $0 FAIL ${course}
    fi
done
# Update course id listing for powerbi desktop if all courses are processed
if [ $# -eq 0 ]; then
    ./helper-scripts/ll-courses.sh --only-ids > ${datadir}/oppikoppi-courses.txt
fi
cd $prevPWD
