#!/bin/bash
#  This file is part of oppikoppi.
#  Copyright (C) 2021 Anssi Gröhn

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# This script runs robot framework script, which downloads moodle logs from yesterday using special account
# and converts them into xAPI statements locally, and sends them forth to local learning locker instance.
send_running=`ps -C oppikoppi_send_all_events.sh -o pid=`
if [ "${send_running}" == "" ]; then
    start=$(date "+%Y-%m-%d %H:%M")
    logger handle-staging-events PROCESSING
    /path/to/Staging/oppikoppi_send_all_events.sh
    if ! [ $? -eq 0 ]; then
	logger handle-staging-events $start FAILED
    fi
else
    logger handle-staging-events EMPTY
fi
